services:

  postgresql_01:
    image: postgres
    container_name: postgresql_01
    restart: always
    volumes:
      - C:\Users\user\Desktop\otus\replecation\postgresql_01:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres024
    networks:
      - app-network
    ports:
      - "3307:3306"

  postgresql_02:
    image: postgres
    container_name: postgresql_02
    restart: always
    volumes:
      - C:\Users\user\Desktop\otus\replecation\postgresql_02/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres024
    networks:
      - app-network
    ports:
      - "3308:3306"
  
  postgresql_03:
    image: postgres
    container_name: postgresql_03
    restart: always
    volumes:
      - C:\Users\user\Desktop\otus\replecation\postgresql_03/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres024
    networks:
      - app-network
    ports:
      - "3309:3306"

networks:
  app-network:
    driver: bridge